# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The best NLP papers
name: "Maciej Gruszczyński"
email: maciek.gruszka@gmail.com
description: Dive into the world of Natural Language Processing at thebestnlppapers.com. Our site ranks the best NLP papers each year based on citation count, providing a simple yet effective resource for researchers, students, and AI enthusiasts.
url: "https://thebestnlppapers.com"
repository: "mcPear/best-papers"
github_username: mcPear

author:
  name: "Maciej Gruszczyński"
  avatar: "/assets/profile.jpeg"
  bio: "Data Scientist"
  links:
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/maciej-gruszczy%C5%84ski-b92013155/"
    - label: "Substack"
      icon: "/assets/substack.svg"
      url: "https://justlearningdatascience.substack.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mcPear/best-papers"
    - label: "Coffee"
      icon: "fa fa-fw fa-coffee"
      url: "https://www.buymeacoffee.com/mcPear"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mcPear/best-papers"
    - label: "Substack"
      icon: "/assets/substack.svg"
      url: "https://justlearningdatascience.substack.com/"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/maciej-gruszczy%C5%84ski-b92013155/"
    - label: "Coffee"
      icon: "fa fa-fw fa-coffee"
      url: "https://www.buymeacoffee.com/mcPear"

atom_feed:
  hide: true

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "contrast"

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor

defaults:
  - scope:
      path: "pages"
    values:
      layout: single
      sidebar:
        nav: "scope_nav"

plugins:
  - jekyll-include-cache

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-VQWRT3PKWG"
